import { PlaceEntry, ProfileSpec } from './types';

// Profile tiếng Anh — trục landmark + tên khu quen thuộc với khách quốc tế.
// 304 địa điểm / 34 tỉnh.
//
// KHÔNG phải bản dịch của vi.ts: "quận 3", "phường 5" gần như không xuất hiện
// trong review tiếng Anh. Ngoại lệ đã thành từ vựng du lịch: District 1/2, Thao Dien.
// Ngược lại EN có Golden Bridge, Lady Buddha, Crazy House, Train Street, Fairy Stream
// — những cái bên VI gần như không ai viết.

export const EN_PLACES: PlaceEntry[] = [
  // ha_noi (tier A)
  { name: 'Hanoi', provinceSlug: 'ha_noi', cadence: 'core' },
  { name: 'Ha Noi', provinceSlug: 'ha_noi', cadence: 'core' },
  { name: 'Hanoi Old Quarter', provinceSlug: 'ha_noi', cadence: 'core' },
  { name: 'Hoan Kiem Lake', provinceSlug: 'ha_noi', cadence: 'core' },
  { name: 'Train Street', provinceSlug: 'ha_noi', cadence: 'core' },
  { name: 'West Lake', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Temple of Literature', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Ho Chi Minh Mausoleum', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Imperial Citadel Thang Long', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Ta Hien Street', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Tran Quoc Pagoda', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Dong Xuan Market', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Long Bien Bridge', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Ba Vi National Park', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Perfume Pagoda', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Duong Lam Ancient Village', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Bat Trang', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Hanoi French Quarter', provinceSlug: 'ha_noi', cadence: 'long' },
  // hcmc (tier A)
  { name: 'Ho Chi Minh City', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Saigon', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'District 1', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Ben Thanh Market', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Bui Vien', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Vung Tau', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Con Dao', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Thao Dien', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'District 2', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'War Remnants Museum', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Cu Chi Tunnels', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Notre Dame Cathedral Saigon', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Nguyen Hue Walking Street', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Landmark 81', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Ho Tram', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Independence Palace', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Back Beach Vung Tau', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Christ the King Statue', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Can Gio', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Cholon', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'District 7', provinceSlug: 'hcmc', cadence: 'long' },
  // da_nang (tier A)
  { name: 'Da Nang', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Danang', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Hoi An', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'My Khe Beach', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Hoi An Ancient Town', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Golden Bridge', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Ba Na Hills', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Marble Mountains', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Son Tra Peninsula', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Dragon Bridge', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'An Bang Beach', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Lady Buddha', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Cham Islands', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'My Son Sanctuary', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Hai Van Pass', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Han Market', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Coconut Village', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Non Nuoc Beach', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Linh Ung Pagoda', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Tam Ky', provinceSlug: 'da_nang', cadence: 'long' },
  // hue (tier A)
  { name: 'Hue', provinceSlug: 'hue', cadence: 'core' },
  { name: 'Hue Imperial City', provinceSlug: 'hue', cadence: 'core' },
  { name: 'Perfume River', provinceSlug: 'hue', cadence: 'core' },
  { name: 'Thien Mu Pagoda', provinceSlug: 'hue', cadence: 'core' },
  { name: 'Khai Dinh Tomb', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Tu Duc Tomb', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Minh Mang Tomb', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Truong Tien Bridge', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Dong Ba Market', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Lang Co Beach', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Bach Ma National Park', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Thuy Xuan Incense Village', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Tam Giang Lagoon', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Thuan An Beach', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Vong Canh Hill', provinceSlug: 'hue', cadence: 'long' },
  // lam_dong (tier A)
  { name: 'Da Lat', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Dalat', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Mui Ne', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Phan Thiet', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Langbiang', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Tuyen Lam Lake', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Datanla Falls', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Crazy House', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Cau Dat Tea Hill', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'White Sand Dunes', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Red Sand Dunes', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Fairy Stream', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Xuan Huong Lake', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Dalat Market', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Elephant Falls', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Pongour Falls', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Ke Ga Lighthouse', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Ta Dung Lake', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Bao Loc', provinceSlug: 'lam_dong', cadence: 'long' },
  // khanh_hoa (tier A)
  { name: 'Nha Trang', provinceSlug: 'khanh_hoa', cadence: 'core' },
  { name: 'Cam Ranh', provinceSlug: 'khanh_hoa', cadence: 'core' },
  { name: 'Phan Rang', provinceSlug: 'khanh_hoa', cadence: 'core' },
  { name: 'Vinh Hy Bay', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Bai Dai Beach', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Doc Let Beach', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Hon Mun', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Ponagar Tower', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Binh Ba Island', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Ninh Chu', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Diep Son Island', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Van Phong Bay', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Hang Rai', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Nam Cuong Sand Dunes', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Ca Na', provinceSlug: 'khanh_hoa', cadence: 'long' },
  // quang_ninh (tier A)
  { name: 'Ha Long Bay', provinceSlug: 'quang_ninh', cadence: 'core' },
  { name: 'Halong Bay', provinceSlug: 'quang_ninh', cadence: 'core' },
  { name: 'Bai Chay', provinceSlug: 'quang_ninh', cadence: 'core' },
  { name: 'Co To', provinceSlug: 'quang_ninh', cadence: 'core' },
  { name: 'Bai Tu Long Bay', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Titop Island', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Sung Sot Cave', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Yen Tu', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Quan Lan', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Van Don', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Tuan Chau', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Mong Cai', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Ngoc Vung', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Ba Vang Pagoda', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Binh Lieu', provinceSlug: 'quang_ninh', cadence: 'long' },
  // ninh_binh (tier A)
  { name: 'Ninh Binh', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Trang An', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Tam Coc', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Mua Cave', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Bai Dinh Pagoda', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Cuc Phuong National Park', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Hoa Lu', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Van Long', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Thung Nham', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Bich Dong Pagoda', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Phat Diem Cathedral', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Tam Chuc Pagoda', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Nam Dinh', provinceSlug: 'ninh_binh', cadence: 'long' },
  // lao_cai (tier A)
  { name: 'Sapa', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Sa Pa', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Fansipan', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Mu Cang Chai', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Cat Cat Village', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Ta Van', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Lao Chai', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Y Ty', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Bac Ha Market', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'O Quy Ho Pass', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Silver Waterfall', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Ham Rong Mountain', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Tram Tau', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Tu Le', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Khau Pha Pass', provinceSlug: 'lao_cai', cadence: 'long' },
  // an_giang (tier A)
  { name: 'Phu Quoc', provinceSlug: 'an_giang', cadence: 'core' },
  { name: 'Chau Doc', provinceSlug: 'an_giang', cadence: 'core' },
  { name: 'Ha Tien', provinceSlug: 'an_giang', cadence: 'core' },
  { name: 'Sao Beach', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Tra Su Forest', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Nam Du', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Hon Son', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Long Beach Phu Quoc', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Sunset Town', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'An Thoi', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Hon Thom', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Rach Gia', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Ba Chua Xu Temple', provinceSlug: 'an_giang', cadence: 'long' },
  // gia_lai (tier A)
  { name: 'Quy Nhon', provinceSlug: 'gia_lai', cadence: 'core' },
  { name: 'Pleiku', provinceSlug: 'gia_lai', cadence: 'core' },
  { name: 'Ky Co', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Eo Gio', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Ghenh Rang', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Bien Ho Lake', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Cu Lao Xanh', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Twin Towers Quy Nhon', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Trung Luong', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Ham Ho', provinceSlug: 'gia_lai', cadence: 'long' },
  // tuyen_quang (tier A)
  { name: 'Ha Giang', provinceSlug: 'tuyen_quang', cadence: 'core' },
  { name: 'Ha Giang Loop', provinceSlug: 'tuyen_quang', cadence: 'core' },
  { name: 'Dong Van', provinceSlug: 'tuyen_quang', cadence: 'core' },
  { name: 'Ma Pi Leng Pass', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Nho Que River', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Lung Cu', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Hoang Su Phi', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Meo Vac', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Quan Ba', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Yen Minh', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Na Hang', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Vuong Palace', provinceSlug: 'tuyen_quang', cadence: 'long' },
  // hai_phong (tier B)
  { name: 'Cat Ba', provinceSlug: 'hai_phong', cadence: 'core' },
  { name: 'Lan Ha Bay', provinceSlug: 'hai_phong', cadence: 'core' },
  { name: 'Cat Ba National Park', provinceSlug: 'hai_phong', cadence: 'mid' },
  { name: 'Do Son', provinceSlug: 'hai_phong', cadence: 'mid' },
  { name: 'Hai Phong', provinceSlug: 'hai_phong', cadence: 'mid' },
  { name: 'Monkey Island', provinceSlug: 'hai_phong', cadence: 'long' },
  { name: 'Viet Hai Village', provinceSlug: 'hai_phong', cadence: 'long' },
  // can_tho (tier B)
  { name: 'Can Tho', provinceSlug: 'can_tho', cadence: 'core' },
  { name: 'Cai Rang Floating Market', provinceSlug: 'can_tho', cadence: 'mid' },
  { name: 'Ninh Kieu', provinceSlug: 'can_tho', cadence: 'mid' },
  { name: 'Son Islet', provinceSlug: 'can_tho', cadence: 'mid' },
  { name: 'Binh Thuy Ancient House', provinceSlug: 'can_tho', cadence: 'long' },
  { name: 'Bat Pagoda', provinceSlug: 'can_tho', cadence: 'long' },
  // thanh_hoa (tier B)
  { name: 'Pu Luong', provinceSlug: 'thanh_hoa', cadence: 'core' },
  { name: 'Sam Son', provinceSlug: 'thanh_hoa', cadence: 'mid' },
  { name: 'Thanh Hoa', provinceSlug: 'thanh_hoa', cadence: 'mid' },
  { name: 'Ho Citadel', provinceSlug: 'thanh_hoa', cadence: 'mid' },
  { name: 'Ben En National Park', provinceSlug: 'thanh_hoa', cadence: 'long' },
  { name: 'Hai Tien Beach', provinceSlug: 'thanh_hoa', cadence: 'long' },
  // nghe_an (tier B)
  { name: 'Cua Lo', provinceSlug: 'nghe_an', cadence: 'core' },
  { name: 'Nghe An', provinceSlug: 'nghe_an', cadence: 'mid' },
  { name: 'Pu Mat National Park', provinceSlug: 'nghe_an', cadence: 'mid' },
  { name: 'Muong Long', provinceSlug: 'nghe_an', cadence: 'mid' },
  { name: 'Kim Lien Village', provinceSlug: 'nghe_an', cadence: 'long' },
  { name: 'Khe Kem Waterfall', provinceSlug: 'nghe_an', cadence: 'long' },
  // quang_tri (tier B)
  { name: 'Phong Nha', provinceSlug: 'quang_tri', cadence: 'core' },
  { name: 'Son Doong', provinceSlug: 'quang_tri', cadence: 'core' },
  { name: 'Paradise Cave', provinceSlug: 'quang_tri', cadence: 'mid' },
  { name: 'Hang En', provinceSlug: 'quang_tri', cadence: 'mid' },
  { name: 'Dong Hoi', provinceSlug: 'quang_tri', cadence: 'mid' },
  { name: 'Phong Nha Ke Bang', provinceSlug: 'quang_tri', cadence: 'mid' },
  { name: 'Vinh Moc Tunnels', provinceSlug: 'quang_tri', cadence: 'long' },
  { name: 'Khe Sanh', provinceSlug: 'quang_tri', cadence: 'long' },
  { name: 'Nhat Le Beach', provinceSlug: 'quang_tri', cadence: 'long' },
  { name: 'Quang Tri', provinceSlug: 'quang_tri', cadence: 'long' },
  // quang_ngai (tier B)
  { name: 'Ly Son', provinceSlug: 'quang_ngai', cadence: 'core' },
  { name: 'Mang Den', provinceSlug: 'quang_ngai', cadence: 'mid' },
  { name: 'Kon Tum', provinceSlug: 'quang_ngai', cadence: 'mid' },
  { name: 'Quang Ngai', provinceSlug: 'quang_ngai', cadence: 'mid' },
  { name: 'Sa Huynh Beach', provinceSlug: 'quang_ngai', cadence: 'long' },
  { name: 'Kon Tum Wooden Church', provinceSlug: 'quang_ngai', cadence: 'long' },
  // dak_lak (tier B)
  { name: 'Buon Ma Thuot', provinceSlug: 'dak_lak', cadence: 'core' },
  { name: 'Phu Yen', provinceSlug: 'dak_lak', cadence: 'mid' },
  { name: 'Tuy Hoa', provinceSlug: 'dak_lak', cadence: 'mid' },
  { name: 'Ganh Da Dia', provinceSlug: 'dak_lak', cadence: 'mid' },
  { name: 'Lak Lake', provinceSlug: 'dak_lak', cadence: 'mid' },
  { name: 'Dray Nur Waterfall', provinceSlug: 'dak_lak', cadence: 'mid' },
  { name: 'Bai Xep', provinceSlug: 'dak_lak', cadence: 'long' },
  { name: 'Xuan Dai Bay', provinceSlug: 'dak_lak', cadence: 'long' },
  { name: 'Mui Dien', provinceSlug: 'dak_lak', cadence: 'long' },
  // tay_ninh (tier B)
  { name: 'Ba Den Mountain', provinceSlug: 'tay_ninh', cadence: 'core' },
  { name: 'Cao Dai Temple', provinceSlug: 'tay_ninh', cadence: 'mid' },
  { name: 'Tay Ninh', provinceSlug: 'tay_ninh', cadence: 'mid' },
  { name: 'Dau Tieng Lake', provinceSlug: 'tay_ninh', cadence: 'mid' },
  { name: 'Tan Lap Floating Village', provinceSlug: 'tay_ninh', cadence: 'long' },
  // cao_bang (tier B)
  { name: 'Ban Gioc Waterfall', provinceSlug: 'cao_bang', cadence: 'core' },
  { name: 'Cao Bang', provinceSlug: 'cao_bang', cadence: 'mid' },
  { name: 'Nguom Ngao Cave', provinceSlug: 'cao_bang', cadence: 'mid' },
  { name: 'Thang Hen Lake', provinceSlug: 'cao_bang', cadence: 'mid' },
  { name: 'Pac Bo', provinceSlug: 'cao_bang', cadence: 'mid' },
  { name: 'Angel Eye Mountain', provinceSlug: 'cao_bang', cadence: 'long' },
  { name: 'Phia Oac', provinceSlug: 'cao_bang', cadence: 'long' },
  // dien_bien (tier B)
  { name: 'Dien Bien Phu', provinceSlug: 'dien_bien', cadence: 'core' },
  { name: 'Dien Bien', provinceSlug: 'dien_bien', cadence: 'mid' },
  { name: 'A Pa Chai', provinceSlug: 'dien_bien', cadence: 'mid' },
  { name: 'Pha Din Pass', provinceSlug: 'dien_bien', cadence: 'mid' },
  { name: 'A1 Hill', provinceSlug: 'dien_bien', cadence: 'long' },
  { name: 'Muong Thanh Valley', provinceSlug: 'dien_bien', cadence: 'long' },
  // phu_tho (tier B)
  { name: 'Mai Chau', provinceSlug: 'phu_tho', cadence: 'core' },
  { name: 'Tam Dao', provinceSlug: 'phu_tho', cadence: 'mid' },
  { name: 'Hoa Binh', provinceSlug: 'phu_tho', cadence: 'mid' },
  { name: 'Hung Temple', provinceSlug: 'phu_tho', cadence: 'mid' },
  { name: 'Xuan Son National Park', provinceSlug: 'phu_tho', cadence: 'long' },
  { name: 'Hoa Binh Lake', provinceSlug: 'phu_tho', cadence: 'long' },
  { name: 'Tay Thien', provinceSlug: 'phu_tho', cadence: 'long' },
  // dong_nai (tier B)
  { name: 'Cat Tien National Park', provinceSlug: 'dong_nai', cadence: 'core' },
  { name: 'Nam Cat Tien', provinceSlug: 'dong_nai', cadence: 'mid' },
  { name: 'Dong Nai', provinceSlug: 'dong_nai', cadence: 'mid' },
  { name: 'Tri An Lake', provinceSlug: 'dong_nai', cadence: 'mid' },
  { name: 'Chua Chan Mountain', provinceSlug: 'dong_nai', cadence: 'long' },
  { name: 'Giang Dien Waterfall', provinceSlug: 'dong_nai', cadence: 'long' },
  // son_la (tier B)
  { name: 'Moc Chau', provinceSlug: 'son_la', cadence: 'core' },
  { name: 'Ta Xua', provinceSlug: 'son_la', cadence: 'mid' },
  { name: 'Son La', provinceSlug: 'son_la', cadence: 'mid' },
  { name: 'Dai Yem Waterfall', provinceSlug: 'son_la', cadence: 'mid' },
  { name: 'Moc Chau Tea Hills', provinceSlug: 'son_la', cadence: 'long' },
  { name: 'Bach Long Glass Bridge', provinceSlug: 'son_la', cadence: 'long' },
  // hung_yen (tier C)
  { name: 'Hung Yen', provinceSlug: 'hung_yen', cadence: 'mid' },
  { name: 'Pho Hien', provinceSlug: 'hung_yen', cadence: 'long' },
  { name: 'Thai Binh', provinceSlug: 'hung_yen', cadence: 'long' },
  // bac_ninh (tier C)
  { name: 'Bac Ninh', provinceSlug: 'bac_ninh', cadence: 'mid' },
  { name: 'Bac Giang', provinceSlug: 'bac_ninh', cadence: 'long' },
  { name: 'Do Temple', provinceSlug: 'bac_ninh', cadence: 'long' },
  // vinh_long (tier C)
  { name: 'Ben Tre', provinceSlug: 'vinh_long', cadence: 'mid' },
  { name: 'Vinh Long', provinceSlug: 'vinh_long', cadence: 'mid' },
  { name: 'An Binh Islet', provinceSlug: 'vinh_long', cadence: 'long' },
  { name: 'Con Phung', provinceSlug: 'vinh_long', cadence: 'long' },
  // dong_thap (tier C)
  { name: 'Sa Dec', provinceSlug: 'dong_thap', cadence: 'mid' },
  { name: 'Tram Chim', provinceSlug: 'dong_thap', cadence: 'mid' },
  { name: 'Cai Be Floating Market', provinceSlug: 'dong_thap', cadence: 'long' },
  { name: 'My Tho', provinceSlug: 'dong_thap', cadence: 'long' },
  { name: 'Thoi Son Island', provinceSlug: 'dong_thap', cadence: 'long' },
  // ca_mau (tier C)
  { name: 'Ca Mau', provinceSlug: 'ca_mau', cadence: 'mid' },
  { name: 'Bac Lieu', provinceSlug: 'ca_mau', cadence: 'mid' },
  { name: 'Cape Ca Mau', provinceSlug: 'ca_mau', cadence: 'long' },
  { name: 'U Minh Forest', provinceSlug: 'ca_mau', cadence: 'long' },
  // lang_son (tier C)
  { name: 'Lang Son', provinceSlug: 'lang_son', cadence: 'mid' },
  { name: 'Mau Son', provinceSlug: 'lang_son', cadence: 'long' },
  { name: 'Bac Son Valley', provinceSlug: 'lang_son', cadence: 'long' },
  // thai_nguyen (tier C)
  { name: 'Ba Be Lake', provinceSlug: 'thai_nguyen', cadence: 'mid' },
  { name: 'Thai Nguyen', provinceSlug: 'thai_nguyen', cadence: 'long' },
  { name: 'Nui Coc Lake', provinceSlug: 'thai_nguyen', cadence: 'long' },
  // ha_tinh (tier C)
  { name: 'Ha Tinh', provinceSlug: 'ha_tinh', cadence: 'mid' },
  { name: 'Thien Cam Beach', provinceSlug: 'ha_tinh', cadence: 'long' },
  { name: 'Ngang Pass', provinceSlug: 'ha_tinh', cadence: 'long' },
  // lai_chau (tier C)
  { name: 'Lai Chau', provinceSlug: 'lai_chau', cadence: 'mid' },
  { name: 'Pu Ta Leng', provinceSlug: 'lai_chau', cadence: 'long' },
  { name: 'Sin Suoi Ho', provinceSlug: 'lai_chau', cadence: 'long' },
];

export const enProfile: ProfileSpec = {
  id: 'en',
  places: EN_PLACES,
  cadence: {
    core: { cadenceDays: 6, windowDays: 12 },
    mid: { cadenceDays: 12, windowDays: 18 },
    long: { cadenceDays: 21, windowDays: 28 },
  },
  pageDepth: {
    A: { core: 5, mid: 3, long: 2 },
    B: { core: 2, mid: 2, long: 1 },
    C: { core: 1, mid: 1, long: 1 },
  },
  intentGroups: [
    ['I stayed', 'we stayed', 'I visited', 'we visited', 'my experience'],
    ['would recommend', "wouldn't recommend", 'worth it', 'not worth', 'worth visiting'],
    ['tourist trap', 'ripped off', 'overpriced', 'scammed', 'disappointed', 'bad experience'],
  ],
  intentLiteral: null,
  // Rỗng: negative tiếng Việt vô nghĩa với query EN và đẩy query lên 43 từ (vỡ trần 32).
  commercialNegatives: [],
  placesPerQuery: 3,
  sites: ['facebook.com'],
};
