import { PlaceEntry, ProfileSpec } from './types';

// Profile tiếng Việt — trục hành chính rút gọn, đúng cách người Việt viết.
// 278 địa điểm / 34 tỉnh.
//
// MAPPING SÁP NHẬP 2025 (bắt buộc đúng):
//   da_nang=Đà Nẵng+Quảng Nam | hcmc=TP.HCM+Vũng Tàu+Bình Dương
//   lam_dong=Lâm Đồng+Bình Thuận+Đắk Nông | khanh_hoa=Khánh Hòa+Ninh Thuận
//   quang_tri=Quảng Trị+Quảng Bình | gia_lai=Gia Lai+Bình Định
//   tuyen_quang=Tuyên Quang+Hà Giang | lao_cai=Lào Cai+Yên Bái
//   an_giang=An Giang+Kiên Giang | dak_lak=Đắk Lắk+Phú Yên
//   quang_ngai=Quảng Ngãi+Kon Tum | phu_tho=Phú Thọ+Vĩnh Phúc+Hòa Bình
//   ninh_binh=Ninh Bình+Nam Định+Hà Nam | thai_nguyen=Thái Nguyên+Bắc Kạn
//   dong_nai=Đồng Nai+Bình Phước | tay_ninh=Tây Ninh+Long An
//   hai_phong=Hải Phòng+Hải Dương | bac_ninh=Bắc Ninh+Bắc Giang
//   vinh_long=Vĩnh Long+Bến Tre+Trà Vinh | dong_thap=Đồng Tháp+Tiền Giang
//   ca_mau=Cà Mau+Bạc Liêu | hung_yen=Hưng Yên+Thái Bình

export const VI_PLACES: PlaceEntry[] = [
  // ha_noi (tier A)
  { name: 'Hà Nội', provinceSlug: 'ha_noi', cadence: 'core' },
  { name: 'Hoàn Kiếm', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Ba Đình', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Tây Hồ', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Đống Đa', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Hai Bà Trưng', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Cầu Giấy', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Long Biên', provinceSlug: 'ha_noi', cadence: 'mid' },
  { name: 'Hà Đông', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Thanh Xuân', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Nam Từ Liêm', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Bắc Từ Liêm', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Sơn Tây', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Ba Vì', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Sóc Sơn', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Đông Anh', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Gia Lâm', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Thanh Trì', provinceSlug: 'ha_noi', cadence: 'long' },
  { name: 'Mê Linh', provinceSlug: 'ha_noi', cadence: 'long' },
  // hcmc (tier A)
  { name: 'TP.HCM', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Sài Gòn', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Vũng Tàu', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'Bình Dương', provinceSlug: 'hcmc', cadence: 'core' },
  { name: 'quận 1', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'quận 3', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'quận 7', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Bình Thạnh', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Phú Nhuận', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Thủ Đức', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Bà Rịa', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'Côn Đảo', provinceSlug: 'hcmc', cadence: 'mid' },
  { name: 'quận 4', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'quận 5', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'quận 6', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'quận 8', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'quận 10', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'quận 11', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'quận 12', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Tân Bình', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Gò Vấp', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Tân Phú', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Bình Tân', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Củ Chi', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Hóc Môn', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Nhà Bè', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Cần Giờ', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Phú Mỹ', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Long Điền', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Xuyên Mộc', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Thủ Dầu Một', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Dĩ An', provinceSlug: 'hcmc', cadence: 'long' },
  { name: 'Thuận An', provinceSlug: 'hcmc', cadence: 'long' },
  // da_nang (tier A)
  { name: 'Đà Nẵng', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Quảng Nam', provinceSlug: 'da_nang', cadence: 'core' },
  { name: 'Hội An', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Hải Châu', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Sơn Trà', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Ngũ Hành Sơn', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Tam Kỳ', provinceSlug: 'da_nang', cadence: 'mid' },
  { name: 'Thanh Khê', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Liên Chiểu', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Cẩm Lệ', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Hòa Vang', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Điện Bàn', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Duy Xuyên', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Núi Thành', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Thăng Bình', provinceSlug: 'da_nang', cadence: 'long' },
  { name: 'Đại Lộc', provinceSlug: 'da_nang', cadence: 'long' },
  // hue (tier A)
  { name: 'Huế', provinceSlug: 'hue', cadence: 'core' },
  { name: 'Thừa Thiên Huế', provinceSlug: 'hue', cadence: 'core' },
  { name: 'Phú Xuân', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Thuận Hóa', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Hương Thủy', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Hương Trà', provinceSlug: 'hue', cadence: 'mid' },
  { name: 'Phong Điền', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Quảng Điền', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Phú Vang', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Phú Lộc', provinceSlug: 'hue', cadence: 'long' },
  { name: 'A Lưới', provinceSlug: 'hue', cadence: 'long' },
  { name: 'Nam Đông', provinceSlug: 'hue', cadence: 'long' },
  // lam_dong (tier A)
  { name: 'Lâm Đồng', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Bình Thuận', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Đà Lạt', provinceSlug: 'lam_dong', cadence: 'core' },
  { name: 'Phan Thiết', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Bảo Lộc', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Mũi Né', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Đức Trọng', provinceSlug: 'lam_dong', cadence: 'mid' },
  { name: 'Lạc Dương', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Đơn Dương', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Lâm Hà', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Di Linh', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Đạ Huoai', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'La Gi', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Hàm Thuận Nam', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Hàm Thuận Bắc', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Tuy Phong', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Bắc Bình', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Gia Nghĩa', provinceSlug: 'lam_dong', cadence: 'long' },
  { name: 'Đắk Mil', provinceSlug: 'lam_dong', cadence: 'long' },
  // khanh_hoa (tier A)
  { name: 'Khánh Hòa', provinceSlug: 'khanh_hoa', cadence: 'core' },
  { name: 'Nha Trang', provinceSlug: 'khanh_hoa', cadence: 'core' },
  { name: 'Ninh Thuận', provinceSlug: 'khanh_hoa', cadence: 'core' },
  { name: 'Cam Ranh', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Phan Rang', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Ninh Hòa', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Cam Lâm', provinceSlug: 'khanh_hoa', cadence: 'mid' },
  { name: 'Vạn Ninh', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Diên Khánh', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Khánh Vĩnh', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Khánh Sơn', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Ninh Hải', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Ninh Phước', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Thuận Bắc', provinceSlug: 'khanh_hoa', cadence: 'long' },
  { name: 'Thuận Nam', provinceSlug: 'khanh_hoa', cadence: 'long' },
  // quang_ninh (tier A)
  { name: 'Quảng Ninh', provinceSlug: 'quang_ninh', cadence: 'core' },
  { name: 'Hạ Long', provinceSlug: 'quang_ninh', cadence: 'core' },
  { name: 'Cẩm Phả', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Uông Bí', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Móng Cái', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Vân Đồn', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Cô Tô', provinceSlug: 'quang_ninh', cadence: 'mid' },
  { name: 'Đông Triều', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Quảng Yên', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Tiên Yên', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Bình Liêu', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Ba Chẽ', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Đầm Hà', provinceSlug: 'quang_ninh', cadence: 'long' },
  { name: 'Hải Hà', provinceSlug: 'quang_ninh', cadence: 'long' },
  // ninh_binh (tier A)
  { name: 'Ninh Bình', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Nam Định', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Hà Nam', provinceSlug: 'ninh_binh', cadence: 'core' },
  { name: 'Hoa Lư', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Tam Điệp', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Phủ Lý', provinceSlug: 'ninh_binh', cadence: 'mid' },
  { name: 'Gia Viễn', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Nho Quan', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Yên Khánh', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Yên Mô', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Kim Sơn', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Ý Yên', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Hải Hậu', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Giao Thủy', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Nghĩa Hưng', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Duy Tiên', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Kim Bảng', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Lý Nhân', provinceSlug: 'ninh_binh', cadence: 'long' },
  { name: 'Thanh Liêm', provinceSlug: 'ninh_binh', cadence: 'long' },
  // lao_cai (tier A)
  { name: 'Lào Cai', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Yên Bái', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Sa Pa', provinceSlug: 'lao_cai', cadence: 'core' },
  { name: 'Bắc Hà', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Bát Xát', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Nghĩa Lộ', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Mù Cang Chải', provinceSlug: 'lao_cai', cadence: 'mid' },
  { name: 'Bảo Thắng', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Bảo Yên', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Mường Khương', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Si Ma Cai', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Văn Bàn', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Văn Yên', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Trấn Yên', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Văn Chấn', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Trạm Tấu', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Lục Yên', provinceSlug: 'lao_cai', cadence: 'long' },
  { name: 'Yên Bình', provinceSlug: 'lao_cai', cadence: 'long' },
  // an_giang (tier A)
  { name: 'An Giang', provinceSlug: 'an_giang', cadence: 'core' },
  { name: 'Kiên Giang', provinceSlug: 'an_giang', cadence: 'core' },
  { name: 'Phú Quốc', provinceSlug: 'an_giang', cadence: 'core' },
  { name: 'Châu Đốc', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Long Xuyên', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Rạch Giá', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Hà Tiên', provinceSlug: 'an_giang', cadence: 'mid' },
  { name: 'Tân Châu', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Tịnh Biên', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Tri Tôn', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Chợ Mới', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Châu Phú', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Thoại Sơn', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Kiên Lương', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Hòn Đất', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Giồng Riềng', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'An Biên', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'U Minh Thượng', provinceSlug: 'an_giang', cadence: 'long' },
  { name: 'Phú Tân', provinceSlug: 'an_giang', cadence: 'long' },
  // gia_lai (tier A)
  { name: 'Gia Lai', provinceSlug: 'gia_lai', cadence: 'core' },
  { name: 'Bình Định', provinceSlug: 'gia_lai', cadence: 'core' },
  { name: 'Quy Nhơn', provinceSlug: 'gia_lai', cadence: 'core' },
  { name: 'Pleiku', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'An Khê', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'An Nhơn', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Hoài Nhơn', provinceSlug: 'gia_lai', cadence: 'mid' },
  { name: 'Chư Sê', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Chư Păh', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Đức Cơ', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Ia Grai', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Kbang', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Tây Sơn', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Phù Cát', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Phù Mỹ', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Tuy Phước', provinceSlug: 'gia_lai', cadence: 'long' },
  { name: 'Vân Canh', provinceSlug: 'gia_lai', cadence: 'long' },
  // tuyen_quang (tier A)
  { name: 'Tuyên Quang', provinceSlug: 'tuyen_quang', cadence: 'core' },
  { name: 'Hà Giang', provinceSlug: 'tuyen_quang', cadence: 'core' },
  { name: 'Đồng Văn', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Mèo Vạc', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Yên Minh', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Quản Bạ', provinceSlug: 'tuyen_quang', cadence: 'mid' },
  { name: 'Hoàng Su Phì', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Xín Mần', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Bắc Quang', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Vị Xuyên', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Na Hang', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Chiêm Hóa', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Sơn Dương', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Hàm Yên', provinceSlug: 'tuyen_quang', cadence: 'long' },
  { name: 'Lâm Bình', provinceSlug: 'tuyen_quang', cadence: 'long' },
  // hai_phong (tier B)
  { name: 'Hải Phòng', provinceSlug: 'hai_phong', cadence: 'core' },
  { name: 'Hải Dương', provinceSlug: 'hai_phong', cadence: 'core' },
  { name: 'Cát Bà', provinceSlug: 'hai_phong', cadence: 'mid' },
  { name: 'Đồ Sơn', provinceSlug: 'hai_phong', cadence: 'mid' },
  // can_tho (tier B)
  { name: 'Cần Thơ', provinceSlug: 'can_tho', cadence: 'core' },
  { name: 'Sóc Trăng', provinceSlug: 'can_tho', cadence: 'core' },
  { name: 'Hậu Giang', provinceSlug: 'can_tho', cadence: 'core' },
  { name: 'Ninh Kiều', provinceSlug: 'can_tho', cadence: 'mid' },
  { name: 'Cái Răng', provinceSlug: 'can_tho', cadence: 'mid' },
  // thanh_hoa (tier B)
  { name: 'Thanh Hóa', provinceSlug: 'thanh_hoa', cadence: 'core' },
  { name: 'Sầm Sơn', provinceSlug: 'thanh_hoa', cadence: 'mid' },
  { name: 'Pù Luông', provinceSlug: 'thanh_hoa', cadence: 'mid' },
  // nghe_an (tier B)
  { name: 'Nghệ An', provinceSlug: 'nghe_an', cadence: 'core' },
  { name: 'Vinh', provinceSlug: 'nghe_an', cadence: 'core' },
  { name: 'Cửa Lò', provinceSlug: 'nghe_an', cadence: 'mid' },
  // quang_tri (tier B)
  { name: 'Quảng Trị', provinceSlug: 'quang_tri', cadence: 'core' },
  { name: 'Quảng Bình', provinceSlug: 'quang_tri', cadence: 'core' },
  { name: 'Phong Nha', provinceSlug: 'quang_tri', cadence: 'mid' },
  { name: 'Đồng Hới', provinceSlug: 'quang_tri', cadence: 'mid' },
  // quang_ngai (tier B)
  { name: 'Quảng Ngãi', provinceSlug: 'quang_ngai', cadence: 'core' },
  { name: 'Kon Tum', provinceSlug: 'quang_ngai', cadence: 'core' },
  { name: 'Lý Sơn', provinceSlug: 'quang_ngai', cadence: 'mid' },
  { name: 'Măng Đen', provinceSlug: 'quang_ngai', cadence: 'mid' },
  // dak_lak (tier B)
  { name: 'Đắk Lắk', provinceSlug: 'dak_lak', cadence: 'core' },
  { name: 'Phú Yên', provinceSlug: 'dak_lak', cadence: 'core' },
  { name: 'Buôn Ma Thuột', provinceSlug: 'dak_lak', cadence: 'mid' },
  { name: 'Tuy Hòa', provinceSlug: 'dak_lak', cadence: 'mid' },
  // tay_ninh (tier B)
  { name: 'Tây Ninh', provinceSlug: 'tay_ninh', cadence: 'core' },
  { name: 'Long An', provinceSlug: 'tay_ninh', cadence: 'core' },
  { name: 'Núi Bà Đen', provinceSlug: 'tay_ninh', cadence: 'mid' },
  // cao_bang (tier B)
  { name: 'Cao Bằng', provinceSlug: 'cao_bang', cadence: 'core' },
  { name: 'Bản Giốc', provinceSlug: 'cao_bang', cadence: 'mid' },
  { name: 'Trùng Khánh', provinceSlug: 'cao_bang', cadence: 'mid' },
  // dien_bien (tier B)
  { name: 'Điện Biên', provinceSlug: 'dien_bien', cadence: 'core' },
  { name: 'Điện Biên Phủ', provinceSlug: 'dien_bien', cadence: 'core' },
  // phu_tho (tier B)
  { name: 'Phú Thọ', provinceSlug: 'phu_tho', cadence: 'core' },
  { name: 'Vĩnh Phúc', provinceSlug: 'phu_tho', cadence: 'core' },
  { name: 'Hòa Bình', provinceSlug: 'phu_tho', cadence: 'core' },
  { name: 'Tam Đảo', provinceSlug: 'phu_tho', cadence: 'mid' },
  { name: 'Mai Châu', provinceSlug: 'phu_tho', cadence: 'mid' },
  // dong_nai (tier B)
  { name: 'Đồng Nai', provinceSlug: 'dong_nai', cadence: 'core' },
  { name: 'Bình Phước', provinceSlug: 'dong_nai', cadence: 'core' },
  { name: 'Biên Hòa', provinceSlug: 'dong_nai', cadence: 'core' },
  // son_la (tier B)
  { name: 'Sơn La', provinceSlug: 'son_la', cadence: 'core' },
  { name: 'Mộc Châu', provinceSlug: 'son_la', cadence: 'mid' },
  { name: 'Tà Xùa', provinceSlug: 'son_la', cadence: 'mid' },
  // hung_yen (tier C)
  { name: 'Hưng Yên', provinceSlug: 'hung_yen', cadence: 'core' },
  { name: 'Thái Bình', provinceSlug: 'hung_yen', cadence: 'core' },
  // bac_ninh (tier C)
  { name: 'Bắc Ninh', provinceSlug: 'bac_ninh', cadence: 'core' },
  { name: 'Bắc Giang', provinceSlug: 'bac_ninh', cadence: 'core' },
  // vinh_long (tier C)
  { name: 'Vĩnh Long', provinceSlug: 'vinh_long', cadence: 'core' },
  { name: 'Bến Tre', provinceSlug: 'vinh_long', cadence: 'core' },
  { name: 'Trà Vinh', provinceSlug: 'vinh_long', cadence: 'core' },
  // dong_thap (tier C)
  { name: 'Đồng Tháp', provinceSlug: 'dong_thap', cadence: 'core' },
  { name: 'Tiền Giang', provinceSlug: 'dong_thap', cadence: 'core' },
  // ca_mau (tier C)
  { name: 'Cà Mau', provinceSlug: 'ca_mau', cadence: 'core' },
  { name: 'Bạc Liêu', provinceSlug: 'ca_mau', cadence: 'core' },
  // lang_son (tier C)
  { name: 'Lạng Sơn', provinceSlug: 'lang_son', cadence: 'core' },
  // thai_nguyen (tier C)
  { name: 'Thái Nguyên', provinceSlug: 'thai_nguyen', cadence: 'core' },
  { name: 'Bắc Kạn', provinceSlug: 'thai_nguyen', cadence: 'core' },
  // ha_tinh (tier C)
  { name: 'Hà Tĩnh', provinceSlug: 'ha_tinh', cadence: 'core' },
  // lai_chau (tier C)
  { name: 'Lai Châu', provinceSlug: 'lai_chau', cadence: 'core' },
];

export const viProfile: ProfileSpec = {
  id: 'vi',
  places: VI_PLACES,
  cadence: {
    core: { cadenceDays: 4, windowDays: 8 },
    mid: { cadenceDays: 8, windowDays: 12 },
    long: { cadenceDays: 14, windowDays: 18 },
  },
  pageDepth: {
    A: { core: 5, mid: 3, long: 2 },
    B: { core: 2, mid: 2, long: 1 },
    C: { core: 1, mid: 1, long: 1 },
  },
  intentGroups: null,
  intentLiteral: 'du lịch',
  commercialNegatives: [
    'combo', 'booking', 'hotline', 'liên hệ', 'zalo',
    'sđt', 'inbox', 'ib', 'tour', 'báo giá',
  ],
  // TikTok's -inbox already covers the same commercial intent as -ib.
  commercialNegativesBySite: {
    'tiktok.com': [
      'combo', 'booking', 'hotline', 'liên hệ', 'zalo',
      'sđt', 'inbox', 'tour', 'báo giá',
    ],
  },
  placesPerQuery: 3,
  // TikTok 21,643 post vs Facebook 23,798 (audit 2026-08-17) — ngang nhau.
  // Comment "TikTok ≈ 0% usable" trong entity_registry.ts đã lỗi thời, KHÔNG dùng.
  // Instagram (64,288 post, nguồn lớn nhất) bật lại; backlog được ghi trong audit.
  sites: ['facebook.com', 'instagram.com', 'tiktok.com'],
};
